name: Docker Image CI

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 5000:5000
          - 6661:6661

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push the backend image
      - name: Build Backend Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/hauntbwickbackend:latest -f ./backend/Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/hauntbwickbackend:latest

      # Build and push the frontend image
      - name: Build Frontend Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/hauntbwickfrontend:latest -f ./frontend/Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/hauntbwickfrontend:latest
